### ISSUE TITLE
Logger program keeps running

### ISSUE THREAD

**Issue by Dwapayan** [splunk/splunk-library-javalogging#111]
After we run the following the program does not exit:

private static Logger LOGGER = LogManager.getLogger(LoggerTest.class);  -> Declared in class scope

LOGGER.info("This is a new string message - info");               -> run from main function

Is some thread still running causing the program to get stuck in execution. The message in the line is sent to splunk but then program does not exit.

Are there ant methods to dispose logger ?

**Comment by shakeelmohamed** [comment]
Hi @Dwapayan, which version of the Java logging library are you using?

**Comment by Dwapayan** [comment]
@shakeelmohamed This is happening with both 1.6.2 and 1.7.1 with JDK 11.0/2

**Comment by shakeelmohamed** [comment]
Can you try adding `LogManager.shutdown();` to your code? We were able to use that as a workaround for older JDKs

**Comment by SuramVishal** [comment]
@shakeelmohamed Unfortunately LogManager.shutdown() itself will not work in all scenarios. 
Scenario : 
Main method calls LogManager.shutdown(), causing HttpEventCollectorLogbackAppender.stop(), which in turn HttpEventCollectorSender.flush(true) and if eventsBatch.size() == 0, we do not close the httpClient. 
I have raised a PR for you to consider. :) 
https://github.com/splunk/splunk-library-javalogging/pull/112

**Comment by fantavlik** [comment]
Fixed in https://github.com/splunk/splunk-library-javalogging/releases/tag/1.7.2

**Comment by fantavlik** [comment]
Please let us know if you continue to see this behavior in version 1.7.2. Thanks!

**Comment by Dwapayan** [comment]
This problem is not solved yet. I tried the 1.7.2 and got the same issue. When 1.7.2 library is added just the declaration causes program to keep running

private static Logger LOGGER = LogManager.getLogger(LoggerTest.class);
